### ISSUE TITLE
Set up discussion board

### ISSUE THREAD

**Issue by fjaguero** [Valencia-JS/valenciajs.org#1]
We should have a place to discuss all the topics related to the community. Maybe a Discourse?

**Comment by DavidBM** [comment]
Discourse me parece una gran ideal.

Lo valoré para Starriser, pero nuestro mercado parece querer foros más "tradicionales".

**Comment by MarioAraque** [comment]
+1 a Discourse.

**Comment by fjaguero** [comment]
¿Dónde lo montamos? ¿Preferencias?

**Comment by MarioAraque** [comment]
En qué quedó esto? Se necesita alguna ayuda/aporte?

**Comment by fjaguero** [comment]
A priori estuvimos hablando de dejarlo de momento hasta que haya más comunidad/discusión, ya que si se hace el esfuerzo de tenerlo funcionando y solo hablamos 3, no aporta mucho.

**Comment by DavidBM** [comment]
Esto se podría retomar no? Ya somos más de 200 miembros en Meetup.

**Comment by fjaguero** [comment]
@DavidBM ¿Crees que vale la pena viendo la acitivdad que hay en el foro de Meetup? En general las preguntas que se hicieron tienen 2-3 respuestas.

**Comment by DavidBM** [comment]
Creo que en ese sentido Meetup deja que desear. Ni MadridJS tiene respuestas en sus foros en Meetup. Igual montar algo tipo https://esdiscuss.org/ (listas de correo + visualización tipo foro) estaría bien.

Es un coste, que tiene un riesgo asociado, pero creo que merece la pena intentarlo. No ahora quizás, pero si para noviembre o o diciembre o ya para principios de 2016. Depende de como vayan las próximas charlas.

**Comment by fjaguero** [comment]
La pregunta es más sobre la necesidad, porque prácticamente nadie ha preguntado nada. En la lista de MadridJS hay veces que la gente manda librerias, preguntas, etc., ¿quizás empezar por promover que se manden cosas por la lista?

**Comment by DavidBM** [comment]
Sí, mejor probar a ver la respuesta de la gente y luego lanzarse a hacer cosas.
En general me gustaría impulsar un poco la charla en la comunidad.
Hay veces en que MadridJS se montan buenos debates por las listas de correos.

**Comment by fjaguero** [comment]
Lo podemos comentar primero por la lista para ver la resputas, ¿cómo lo ves?

**Comment by fjaguero** [comment]
Y si montamos un Slack para probar @DavidBM, es más inmediato para comunicarse con otros y coste casi 0 de implementación. Como la gente de BarcelonaJS http://invite.barcelonajs.org/

**Comment by DavidBM** [comment]
Me gusta. Creia que había contestado a esto, pero se ve que no y encima me han pillado unas vacaciones en medio. Bueno, pues eso, el slack me parece de lujo.

**Comment by fjaguero** [comment]
Me lo asigno para darle una vuelta, lo que sea voy dejando comentarios, ¿te parece?

**Comment by DavidBM** [comment]
ok!

**Comment by fjaguero** [comment]
Ya tenemos Slack de moment ;) http://valenciajs.herokuapp.com/
