### ISSUE TITLE
Arrange first meetup

### ISSUE THREAD

**Issue by fjaguero** [Valencia-JS/valenciajs.org#2]
Hi everyone!

The idea of ValenciaJS is to create a community to empower the developers from Valencia (internationals are welcome!). This may be done via collective hacking, talks or even having some drinks. I think that we can start by having some drinks at the end of the month and talk about what we want do to next. 

**What do you think?**

**Comment by jonastg** [comment]
It's a good idea! We can have these beers and to talk about the purpose or espectatives of the group. For 19th week or  26th?

**Comment by fjaguero** [comment]
I think we can meet the 26th. They are 12 people on the list now so let's wait a little more and see if it grows. Any venue recommendation? :smile:

**Comment by AlvaroFranco** [comment]
I guess that Swift Pizzeria at Xuquer might be a good place to meet. Just because of the name :stuck_out_tongue:

**Comment by jonastg** [comment]
haha it seems a place for Apple lovers, nearby there is an american style restauran with good hamburguers, The Black Turtle :)

**Comment by fjaguero** [comment]
I just asked via the twitter account to get some recommendations :smile:

**Comment by fjaguero** [comment]
We will be doing this at GeeksHubs. Confirmed date this week!
