### ISSUE TITLE
Set up job board

### ISSUE THREAD

**Issue by fjaguero** [Valencia-JS/valenciajs.org#3]
Hola,

Nos comentan via twitter (@carlesba) de montar en algún momento un tablón de anuncions de JavaScript en Valencia. ¿Cómo lo ven?

**Comment by MarioAraque** [comment]
Yo lo veo muy bien. Me parece una buena idea.

**Comment by fjaguero** [comment]
Lo podemos comentar en el siguiente evento.

**Comment by fjaguero** [comment]
Estamos usando el discussion board de Meetup.
