### ISSUE TITLE
Join next JS CodeRetreat

### ISSUE THREAD

**Issue by antoniobusrod** [Valencia-JS/valenciajs.org#4]
Hello, is JS CodeRetreat of your interest? Maybe it is a good idea join next JS CodeRetreat at september.

http://jscoderetreat.com/

Cheers!

**Comment by DavidBM** [comment]
Welcome!

In my opinion it would be a great idea! 

@fjaguero  ¿What's your opinion?

**Comment by fjaguero** [comment]
Of course! Is anyone already organizing this in Valencia or should we contact a place to host it and add it on the JS CodeRetreat website?
