### ISSUE TITLE
Talk proposal: ES6 introduction for Node.js

### ISSUE THREAD

**Issue by antoniobusrod** [Valencia-JS/valenciajs.org#5]
Cause Node.js version 4 has been released last Tuesday, I would like to do a talk about how to use new ES6 features in a Node.js application as example!

**Comment by fjaguero** [comment]
Can you move the issue to the ![talks](https://github.com/Valencia-JS/talks) repo? :smile:

**Comment by antoniobusrod** [comment]
Done!

**Comment by DavidBM** [comment]
@antoniobusrod perdón, he estado inactivo un tiempo por problemas de trabajo. 
Por mi parte organizamos la charla. Además tengo la idea de justo después de la charla hacer un taller de node y ES6 ligero. Así tenemos la jornada completa. :)

¿Qué te parece?
