### ISSUE TITLE
Organizador de ValenciaJS

### ISSUE THREAD

**Issue by DavidBM** [Valencia-JS/valenciajs.org#6]
Hola a todos!

Para los que no me conozcáis soy el actual organizador de ValenciaJS.

**TL;DR**: Me mudo a Alemania a finales de mes y no puedo estar presencialmente para organizar eventos, por lo que si alguien quiere ayudar a la comunidad ahora es el momento.

En estos últimos meses han cambiado muchas cosas. Antes pensaba que iba a quedarme en Valencia durante tiempo y que iba a poder llevar ValenciaJS al menos el primer medio año de 2016. La cosa ha sido un poco distinta. Me marcho a Alemania, mi proyecto no ha salido bien y después de dos años y viendo la oportunidad de salir de España, me lanzo a la aventura. Los que sigáis el proyecto lo veréis en unos días.

**¿Qué significa esto?** Que no voy a estar presencialmente en Valencia para organizar eventos/quedadas. 

Si alguien le gusta la comunidad que estamos creando y quiere aportar un poco a que siga creciendo **puede ayudarnos o incluso, poco a poco, ir tomando las riendas. Siempre con mi ayuda**, de la misma forma que @fjaguero me ayudó a mi. 

Este hilo es para organizarnos en este tema, que la gente proponga ideas, sea proponerse para llevar la comunidad o proponer un cambio de sistema organizativo. Esto es de todos y todos tenemos que decidir.

Lo dicho, todos a hablar!

**Comment by saruba** [comment]
Mucha suerte David en tu nueva aventura. Y muchas gracias por tu trabajo.

**Comment by antoniobusrod** [comment]
Mucha suerte David y cuenta con mi ayuda para colaborar/organizar en ValenciaJS

**Comment by fjaguero** [comment]
Lo mismo que los dos comments anteriores. ¡A por el 3º organizador de ValenciaJS! En Febrero ya cumple 1 año.

**Comment by alferpal** [comment]
Contad conmigo

**Comment by jonastg** [comment]
Buenas! Yo estoy dispuesto a tener un papel más activo a nivel organizativo, pero al final el tiempo que le pueda dedicar es limitado y para que una comunidad se mantenga hay que mimarla. Creo que lo ideal sería que hubiera 2 ó 3 personas que asumieran la organización, así cuando una persona no pueda dedicarle todo el tiempo que se requiera o estar disponible, lo puede hacer otra. Así es más fácil no quemarse.

Por otro lado, como esto ha surgido por diferentes canales no recuerdo bien dónde lo leí, pero se hablaba de crear una comunidad para NodeJS y existe ya otra para AngularJS. La percepción que tengo es que en Valencia tenemos muchas comunidades diferentes y muchas veces la asistencia es más o menos reducida. Creo que sería mejor agrupar y tener una comunidad más grande y que a la larga la gente esté más comprometida. Al final NojeJS, AngularJS o el próximo framework js que se ponga de moda, forman parte del ecosistema de Javascript.

**Comment by josesegarra** [comment]
David, mucha suerte en esta nueva etapa !!

Mi tiempo tambien es bastante limitado, y creo que funcionara en la organizacion. Aunque podria participar en acciones puntuales.

Por otro lado, las dos ideas de jonastg ("una organizacion compartida" y "no fraccionar los grupos de JS") me parecen buenas y coherentes

**Comment by antoniobusrod** [comment]
qué os parece si hacemos una reunión para hablar sobre cómo enfocar ValenciaJS con las ideas que han surgido hasta ahora?

**Comment by alferpal** [comment]
En la línea de @antoniobusrod igual podríamos plantear organizar un meeting más pequeño (asumo que no todo el mundo querrá participar de la organización) en alguna cafeteria o algo así y que se presente el que quiera colaborar

**Comment by jonastg** [comment]
Se me olvidó comentarlo antes, muchas gracias por estar ahí David y mucha suerte en Alemania.

Respecto a quedar ¿qué os parece la semana que viene? Así dejamos lo que queda de esta semana para tener más oponiones sobre el tema.

**Comment by fidelab** [comment]
Gracias por el trabajo David.

También creo que es interesante que nos sentemos. La semana que viene es un
poco complicada por las fechas que son, y habrá gente ya de vacaciones,
otros fuera, etc. Podemos intentar quedar esta semana.

¿Os viene mejor esta semana o la que viene?

2015-12-14 17:51 GMT+01:00 Jonas Talavera notifications@github.com:

> Se me olvidó comentarlo antes, muchas gracias por estar ahí David y mucha
> suerte en Alemania.
> 
> Respecto a quedar ¿qué os parece la semana que viene? Así dejamos lo que
> queda de esta semana para tener más oponiones sobre el tema.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Valencia-JS/valenciajs.org/issues/6#issuecomment-164492044
> .

## 

Fidel Añó Bernat

**Comment by jonastg** [comment]
Yo podría miércoles o jueves a última hora

**Comment by alferpal** [comment]
Esta semana lo veo mejor. Yo por las tardes cuando veáis.

**Comment by fjaguero** [comment]
Yo desde lejos sigo aportando el granito con el contenido que comparto via Twitter. Si puedo hacer algo más me dicen.

**Comment by antoniobusrod** [comment]
yo lo tengo complicado esta semana, pero para que sea todo más sencillo, acabo de crear este doodle para que pongamos disponibilidad de días y horas por la tarde. He elegido un lugar cercano a la universidad, pero vamos, entre los que asistamos/asistan se puede elegir.
http://doodle.com/poll/7saip65myhsdzyq4

**Comment by DavidBM** [comment]
Gracias chicos! :D

Yo puedo todas las tardes, así que contad conmigo en la reunión. De todas formas, le doy prioridad, así que si sale algo la reunión tiene más importancia.

Mi experiencia es que unir comunidades es dificil. Aparecen y desaparecen pero lo importante es la gente. Pueden existir varias comunidades compartiendo más del 90% de los miembros. 

Personalmente veo interesante que se hagan eventos compartidos, más que nada por que se podrían hacer mejores eventos y atraer a más gente. Los espacios como geekshubs y las naves estarán encantados de acoger eventos de un tamaño considerable. 

También, si sois varios organizadores todo será más fácil, llevarlo todo uno solo es complejo. 

Os ayudaré con todo lo que pueda! Aquí y en Alemania! :D

**Comment by jonastg** [comment]
Las opciones son lunes o martes a falta de que Alex actualice, aunque creo
que la mejor opción será el martes.

**Comment by antoniobusrod** [comment]
@alferpal puedes actualizar la encuesta?
Creo que sería buena idea ir cerrando el día de la reunión (hoy-mañana), y si no puede ser antes de Navidad, organizamos la reunión en enero.

**Comment by alferpal** [comment]
Hecho, que estaba terminando de comer. 

Lo más votado sale martes si no he mirado mal

**Comment by antoniobusrod** [comment]
Entonces el martes es el mejor día para todos. Propuestas de lugar para
celebrar la reunión?

Antonio Bustos
http://antonio.busrod.net

**Comment by DavidBM** [comment]
Podemos irnos a tomar algo y hablar del tema. Si queréis algún sitio bien de precio está el castillo, al lado de geekshubs. Si no podemos ir a zonas como el cedro o benimaclet. Como prefiráis.

**Comment by antoniobusrod** [comment]
Qué os parece si quedamos martes 29 a las 19h en la puerta de geekshub y de ahí nos trasladamos al lugar que elijamos?

**Comment by fidelab** [comment]
Por mi perfecto.

On Thu, Dec 17, 2015 at 12:41 PM, Antonio Bustos notifications@github.com
wrote:

> Qué os parece si quedamos martes 29 a las 19h en la puerta de geekshub y
> de ahí nos trasladamos al lugar que elijamos?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Valencia-JS/valenciajs.org/issues/6#issuecomment-165431795
> .

## 

Fidel Añó Bernat

**Comment by jonastg** [comment]
Vale, por mi ideal también.

**Comment by alferpal** [comment]
Bien

**Comment by DavidBM** [comment]
A mi me pillará llegando a Berlín, pero quedad y apuntad las conclusiones. 

Para haceros una idea, cosas que gestionamos ahora:
- Meetup (de pago)
- Github
- Twitter (ahora lo lleva @fjaguero y está haciendo un excelentísimo trabajo)

Tanto en Github como en Meetup se pueden poner permisos para que gestionéis nuevos eventos y moderéis la comunidad.

En el meetup, por ejemplo, tenemos un mensaje de MeetMobile para que participemos con ellos (http://www.meetup.com/es/members/131972652/?op=&memberId=131972652), es decir, oportunidades hay y en cuanto cojáis tareas esto se pone en marcha :)

Sea como sea, dejad apuntado lo que habléis y las conclusiones. Suerte! :D

**Comment by antoniobusrod** [comment]
No os olvidéis que hemos quedado esta tarde a las 19h en la puerta de geekshub. De ahí nos trasladamos al lugar que elijamos. Hasta luego!

**Comment by alferpal** [comment]
Hemos visto que estábamos los que podíamos ser, dado un pequeño margen y marchado. Si alguien aparece más tarde o se quiere unir que avise
